#!/bin/sh  
set -eu

unset DISPLAY

escone() {
    printf %s\\n "$1" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/"
}

winpaths() {
    for arg; do
        if [ -e "$arg" ]; then
            escone "$(winepath -w "$arg")"
        else
            escone "$arg"
        fi
    done
    echo " "
}

winenv() {
    wine cmd /c "echo $1" | tr -d '\r'
}
winenv %PROGRAMFILES%
winepath -u "$(winenv %PROGRAMFILES%)"

PROGFILES_PATH="$(winepath -u "$(winenv %PROGRAMFILES%)")"

INNO_BIN="Inno Setup 6/ISCC.exe"
INNO_PATH="${PROGFILES_PATH}/${INNO_BIN}"

echo eval set -- "$(winpaths "$@")"
eval set -- "$(winpaths "$@")"

echo exec wine "$INNO_PATH" "$@"
exec wine "$INNO_PATH" "$@"
