#!/bin/sh  
unset DISPLAY  
scriptname=$(winepath -w "JSignPdf.iss")
distdir=$(winepath -w "$1")
outputdir=$(winepath -w "$2")

wine "C:\Program Files (x86)\Inno Setup 5\ISCC.exe" "$scriptname" "/dDistDir=${distdir}" "/dOutputDir=${outputdir}" "$3" "$4" "$5" "$6" "$7" "$8" "$9"
